### ISSUE TITLE
mia 你好,咨询一下readme.md文件是用什么软件写的?

### ISSUE THREAD

**Issue by fencesitter1** [miawithcode/react-advance#1]
感觉你写的readme文件条理还蛮清晰的,每个hook的使用都有链接跳转到具体的jsx文件.想学习一下这样的做法,不知道您是在什么软件下写的readme文件,就是在vscode里直接写的么?

**Comment by miawithcode** [comment]
你好！`README.md`文件就是直接在VS Code里写的。只需要加上代码文件和`README.md`文件的相对路径就能直接跳转到具体的`jsx`文件里，比如：`./src/project/myProject.jsx`
